### ISSUE TITLE
Hi.

### ISSUE THREAD

**Issue by ghost** [makulik/sttcl#3]
Hello, i saw on stackoverflow that you are very good in c++ can you work for me ? Or if you not want to work maybe some help xD  Thanls.

**Comment by makulik** [comment]
What are you willing to pay per hour?

**Comment by makulik** [comment]
What are you willing to pay per hour?

**Comment by Ira0134** [comment]
well, i'm not so familir with c++ jobs. Tell me a price. :)

**Comment by makulik** [comment]
Well the actual price per hour would be ~73 EUR (~82,5 USD). 
And you should disclose clearly what you want me to do. 
For plain tutoring (teaching) I'd probably charge a higher price per hour (not under 120 EUR (~135,5 USD).

**Comment by makulik** [comment]
You might contact me at my official eMail address: g-makulik (at) t-online.de directly, if you're still interested.

**Comment by Ira0134** [comment]
yes, i'm still interested.I send you an email
